[workspace]
resolver = "3"
members = [
    "miniarg",
    "miniarg_derive",
]

[workspace.package]
# these apply to all crates
version = "0.5.0"
authors = ["Niklas Sombert <niklas@ytvwld.de>", "threadexio <pzarganitis@gmail.com>"]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/YtvwlD/miniarg"

[patch.crates-io]
miniarg_derive = { path = "miniarg_derive" }
