[package]
name = "miniarg_derive"
version.workspace = true
authors.workspace = true
description = "custom derive for miniarg"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn =  { version = "3", features = [ "extra-traits" ] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
version-sync = "0.9"
