[package]
name = "miniarg_derive"
version = "0.1.0"
authors = ["Niklas Sombert <niklas@ytvwld.de>"]
edition = "2018"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
